steps:
  - name: maven:3.6.0-jdk-11-slim
    entrypoint: "mvn"
    args: ["clean", "install", "-q"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "eu.gcr.io/$PROJECT_ID/ryan-portfolio:$SHORT_SHA", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "eu.gcr.io/$PROJECT_ID/ryan-portfolio:$SHORT_SHA"]
  - name: 'bash'
    script: |
      sed -i "s/{{TAG}}/$SHORT_SHA/g" service.yaml
      cat service.yaml
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "services"
      - "replace"
      - "--region"
      - "europe-west1"
      - "service.yaml"
images:
  - "eu.gcr.io/$PROJECT_ID/ryan-portfolio:$SHORT_SHA"
